### ISSUE TITLE
Stop working after reboot

### ISSUE THREAD

**Issue by lgorek** [nanab/Flowmeter#10]
Hello
I have an weird problem. When i add new flow sensor to my CBPi everything is ok. It show flow and total. But when i reboot the system, flow meter stop working at next startup system. I notice then i have two options to fix it:

1. Rename sensor name for example Flow1 change to Flow11
2. Delete and add the same sensor.

Why happend like this ? How to fix it. I have for now connected one flowmeter but when i will tested i want connected 3pcs but for now i dont know where search the error. Its very annoying problem. 

Best Regards.

**Comment by nanab** [comment]
Hi i dont have any CBp system setup anymore so im sorry but i cant test or fix anything. My best tips is that you check on the craftbeerpi group on facebook if there is anyone that can help you
