### ISSUE TITLE
Setup for different flow sensors (self.hetz)

### ISSUE THREAD

**Issue by CarstenBartens** [nanab/Flowmeter#3]
Hi 
Thank you for this wonderful plugin - I have 2 different flow meters and would like to be able to use these in same brew setup. 
One sensor has following data:
Flow rate pulse characteristics: Frequency (Hz) = 7.5 * Flow rate (L/min)
Other sensor has:
Flow rate pulse characteristics: Frequency (Hz) = 5.0 * Flow rate (L/min)

You have this is code line 51 (could this be an user input)
Could you make this "7.5" & "5.0" as a setting on the sensor setup page ? (Default 7.5)

**Comment by nanab** [comment]
Hi!

Im almost finnished whit this implentation as you can use this value to calibrate the sensors. I only have som testing to do and are planned to release the update now this weekend.

**Comment by nanab** [comment]
Hi! i have pushed a commit whit this implentation. you now can set the hertz on the sensor setup page. You have to restart craftbeerpi when you change this value. 
i dont have two flowsensors so can you please test so it works whit different values on them?

**Comment by CarstenBartens** [comment]
I have now tested it and set my value to 5 and 9 liters was measured to 8 - this could be the sensor BUT 10 liters stops at 2 liters measured by the sensor ( think there is some thing wrong in the calculation).

**Comment by nanab** [comment]
Hi sorry that i havent responded on this. I have been away on a long vacation. 
I have ordered a few extra sensors so i can setup o multi sensor testing system.
I will be back on this as soon as i get the sensors.

**Comment by nanab** [comment]
very late answear but your problem was probably an error in the code that stopped the step if it was over 10 liters.

**Comment by bandaxadibar** [comment]
Hello... I'm preparing the connection of the flowmeter, but I have a doubt regarding the resistor 10k to GPIO.. I connect in serie or pull up with the positive?
