### ISSUE TITLE
Help with flowmeter setup

### ISSUE THREAD

**Issue by Philusha1983** [nanab/Flowmeter#6]
Hello,
I connected all required parts as you described. made the setup, but can't see any changes in the flowmeter widget.
Any suggestion how to troubleshoot it?

![flow wiring](https://user-images.githubusercontent.com/7344475/35191659-380cc0e8-fe89-11e7-85c1-bc24839e34c3.JPG)
![flow setup](https://user-images.githubusercontent.com/7344475/35191661-3dd97dc2-fe89-11e7-8c53-1c4f89f06b1e.JPG)
![flow specs](https://user-images.githubusercontent.com/7344475/35191663-43f189c0-fe89-11e7-91de-fe26d837b08d.JPG)
![img_20180117_170127](https://user-images.githubusercontent.com/7344475/35191666-49ddcf4c-fe89-11e7-8a1b-3a889a3ca61d.jpg)

**Comment by nanab** [comment]
Have you dubbel checked which wire that is 5v, gnd and signal? According to the details to tour sensor you should have 7.5 as hertz.

**Comment by Philusha1983** [comment]
​​
I triple checked the wirings.
The flowmeter shoud be 7.5 hearts * litres/minute as it writen in
adafruit website.


*Philip* :)

**Comment by nanab** [comment]
On the setup pic you have choosen pin 25. but on raspberry its connected to pin 26.

**Comment by Philusha1983** [comment]
Well, I reconnect it again with red connected to 3.3v and it worked.
Any reason why not to connect it to pin 3.3v?

**Comment by nanab** [comment]
The only reason that i have it on 5v is that the specs for my flowmeter was 5v.
