### ISSUE TITLE
Wrong total flow

### ISSUE THREAD

**Issue by mreucker** [nanab/Flowmeter#7]
When i prog 25l it stops by 3l,
when I prog 4l it makes it right.
By prog 12l it stops at 2l.

Can someone help?

**Comment by mreucker** [comment]
Eyery programmed toltal flows over 10 false.
Programmed flows under 10 works fine.

**Comment by nanab** [comment]
I have pushed an update that will fix this.

**Comment by mreucker** [comment]
Now it works great, thanks.
